- name: Install dependency packages.
  yum:
    name: "{{item}}"
    state: present
  with_items:
        - apr-devel 
        - apr-util-devel 
        - pcre-devel 
        - gcc
        - java
  become: yes

- name: Create project User
  user:
        name: "{{project_user}}"
  become: yes
