- hosts: redhat
  gather_facts: no
  become: yes
  tasks: 
    - name: Install web server
      yum: 
        name: httpd
        state: installed
      notify: restart-httpd

  handlers:
    - name: restart-httpd
      service:
        name: httpd
        state: restarted
